version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: YourSecurePass123!
      POSTGRES_DB: docdb
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000","9001:9001"]
    volumes: [miniodata:/data]
  createbucket:
    image: minio/mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing local/document-manager;
      mc anonymous set download local/document-manager;
      exit 0;
      "
  backend:
    build: ./backend
    environment:
      PORT: 3001
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: YourSecurePass123!
      DB_NAME: docdb
      JWT_SECRET: ChangeThisSecret
      TWOFA_ENABLED: "false"
      FRONTEND_ORIGIN: http://localhost
      S3_BUCKET: document-manager
      S3_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_FORCE_PATH_STYLE: "true"
      SEED: "true"
    depends_on: [db, minio]
  frontend:
    build: ./frontend
    depends_on: [backend]
    ports: ["80:80"]
volumes:
  dbdata:
  miniodata:
